#!/usr/bin/env bash
# Interactive .env setup for production deployment.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env"

if [[ -f "$ENV_FILE" ]]; then
  echo ".env already exists at $ENV_FILE"
  read -r -p "Overwrite? (y/N): " ans
  if [[ "${ans,,}" != "y" ]]; then
    echo "Keeping existing .env"
    exit 0
  fi
fi

read -r -p "Public site URL (what users visit, e.g. https://liaqatrice.com): " APP_URL
if [[ -z "$APP_URL" ]]; then
  echo "Site URL is required."
  exit 1
fi

read -r -p "App listen port [8010]: " PUBLIC_PORT
PUBLIC_PORT="${PUBLIC_PORT:-8010}"

HOST="$(echo "$APP_URL" | sed -E 's#https?://([^/:]+).*#\1#')"

read -r -p "Admin username [admin]: " ADMIN_USER
ADMIN_USER="${ADMIN_USER:-admin}"

read -r -s -p "Admin password: " ADMIN_PASS
echo ""
ADMIN_PASS="${ADMIN_PASS:-$(openssl rand -base64 16 2>/dev/null || echo change-me-now)}"

SECRET_KEY="$(openssl rand -base64 48 2>/dev/null || python3 -c 'import secrets; print(secrets.token_urlsafe(48))')"

cat > "$ENV_FILE" <<EOF
# Generated by deploy-env-init.sh — $(date -Iseconds)

# --- Frontend ---
VITE_PORT=3000
VITE_HOST=0.0.0.0
VITE_API_URL=

# --- Backend (internal) ---
BACKEND_HOST=127.0.0.1
BACKEND_PORT=8006

# --- Public / deploy ---
PUBLIC_PORT=${PUBLIC_PORT}
APP_URL=${APP_URL}
CORS_ORIGINS=${APP_URL}

# --- Django production ---
DJANGO_SECRET_KEY=${SECRET_KEY}
DJANGO_DEBUG=false
ALLOWED_HOSTS=${HOST},localhost,127.0.0.1

# --- Admin panel ---
ADMIN_USERNAME=${ADMIN_USER}
ADMIN_PASSWORD=${ADMIN_PASS}

# --- Optional ---
GEMINI_API_KEY=
DISABLE_HMR=true
EOF

chmod 600 "$ENV_FILE"
echo ""
echo "✓ Created $ENV_FILE"
echo "  Public URL:  $APP_URL"
echo "  Listen port: $PUBLIC_PORT"
echo "  Admin:       $ADMIN_USER / (password you entered)"
echo ""
echo "Next steps:"
echo "  npm run deploy:build"
echo "  npm run service:install   # recommended"
echo "  npm run deploy:start      # or manual start"
