#!/usr/bin/env bash
# Interactive .env setup for production deployment.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env"

if [[ -f "$ENV_FILE" ]]; then
  echo ".env already exists at $ENV_FILE"
  read -r -p "Overwrite? (y/N): " ans
  if [[ "${ans,,}" != "y" ]]; then
    echo "Keeping existing .env"
    exit 0
  fi
fi

read -r -p "Server IP or domain (e.g. 203.0.113.10 or liaqatrice.com): " HOST
read -r -p "Public port [8010]: " PUBLIC_PORT
PUBLIC_PORT="${PUBLIC_PORT:-8010}"

if [[ "$PUBLIC_PORT" == "80" ]]; then
  APP_URL="http://${HOST}"
else
  APP_URL="http://${HOST}:${PUBLIC_PORT}"
fi

read -r -p "Admin username [admin]: " ADMIN_USER
ADMIN_USER="${ADMIN_USER:-admin}"

read -r -s -p "Admin password: " ADMIN_PASS
echo ""
ADMIN_PASS="${ADMIN_PASS:-$(openssl rand -base64 16 2>/dev/null || echo change-me-now)}"

SECRET_KEY="$(openssl rand -base64 48 2>/dev/null || python3 -c 'import secrets; print(secrets.token_urlsafe(48)')"

cat > "$ENV_FILE" <<EOF
# Generated by deploy-env-init.sh — $(date -Iseconds)

# --- Frontend ---
VITE_PORT=3000
VITE_HOST=0.0.0.0
VITE_API_URL=

# --- Backend (internal, nginx proxies /api) ---
BACKEND_HOST=127.0.0.1
BACKEND_PORT=8006

# --- Public / deploy ---
PUBLIC_PORT=${PUBLIC_PORT}
SERVER_NAME=${HOST}
APP_URL=${APP_URL}
CORS_ORIGINS=${APP_URL}

# --- Django production ---
DJANGO_SECRET_KEY=${SECRET_KEY}
DJANGO_DEBUG=false
ALLOWED_HOSTS=${HOST},localhost,127.0.0.1

# --- Admin panel ---
ADMIN_USERNAME=${ADMIN_USER}
ADMIN_PASSWORD=${ADMIN_PASS}

# --- Optional ---
GEMINI_API_KEY=
DISABLE_HMR=true
EOF

chmod 600 "$ENV_FILE"
echo ""
echo "✓ Created $ENV_FILE"
echo "  Site URL:  $APP_URL"
echo "  Admin:     $ADMIN_USER / (password you entered)"
echo ""
echo "Next steps:"
echo "  npm run deploy:build"
echo ""
echo "  With sudo (nginx):     npm run deploy:install"
echo "  Without sudo (VPS):    npm run deploy:start"
